name: Build and deploy Attendance App to Azure Web App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev python3-opencv cmake build-essential
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel setuptools
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          
          # Clean requirements files first
          if [ -f requirements.txt ]; then
            # Remove any non-package lines from requirements.txt
            grep -v "^#\|^-\|^$\|---" requirements.txt > clean_requirements.txt || echo "flask" > clean_requirements.txt
            pip install -r clean_requirements.txt
          fi
          
          if [ -f project_requirement.txt ]; then
            # Remove any non-package lines from project_requirement.txt
            grep -v "^#\|^-\|^$\|---" project_requirement.txt > clean_project_requirements.txt || echo "" > clean_project_requirements.txt
            if [ -s clean_project_requirements.txt ]; then
              pip install -r clean_project_requirements.txt
            fi
          fi
          
          # Install core dependencies
          pip install opencv-python-headless face-recognition numpy pandas flask
      
      - name: Clean up and package
        run: |
          rm -rf venv/ .git/ **pycache**/
          find . -name "*.pyc" -delete
          # Remove temporary clean files
          rm -f clean_requirements.txt clean_project_requirements.txt
          zip -r release.zip .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Unzip artifact
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'atten-gro'
          slot-name: 'Production'
